config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  devise_for :users
  devise_scope :user do
    get 'sign_in', to:'users/sessions#new'
    post 'sign_in', to:'users/sessions#create'
    get 'sign_up', to:'users/registrations#new'
    post 'sign_up', to:'users/registrations#create'
    get 'sign_out',to:'users/sessions#destroy'
    get 'forgot_password',to:'users/passwords#new'
    post 'forgot_password',to:'users/passwords#create'
    get 'reset_password',to:'users/passwords#edit'
    put 'reset_password',to:'users/passwords#update'
  end

  namespace :admin do
    get '/', to:'dashboard#index', as: :stock
    get 'day_bar', to:'dashboard#day_bar'
    resources :chains do
      resources :markets
    end
    resources :strategies do
      member do
        get 'change_fettle'
      end
    end
    resources :bills
    resources :balances
  end

  namespace :api do
    get 'hit_markets', to:'markets#hit_markets'
    get 'hit_day_bar', to:'markets#hit_day_bar'
    get 'hit_balance', to:'markets#hit_balance'
  end

end

app/models/strategy.rb
# t.integer "chain_id", limit: 4
# t.float   "total",    limit: 24 #持有数量等值 USDT
# t.float   "bulk",     limit: 24 #持有数量
# t.float   "procure",  limit: 24 #单次购买的等值 USDT
# t.float   "in_price",  limit: 24 #买入的最高价
# t.float   "out_price", limit: 24 #卖出的最低价
# t.boolean "fettle"

class Strategy  < ActiveRecord::Base
  belongs_to :chain
  scope :state_dc, ->{ order(fettle: :desc) }
  self.per_page = 10

end

app/controllers/admin/strategies_controller.rb
class Admin::StrategiesController < Admin::BaseController
  before_action :set_strategy, only:[:edit, :update, :destroy, :change_fettle]

  def index
    @points = Strategy.state_dc.paginate(page:params[:page])
  end

  def new
    @point = Strategy.new
  end

  def create
    @point = Strategy.new(strategy_params)
    if @point.save
      redirect_to admin_strategies_path, notice: '策略添加成功'
    else
      flash[:warn] = "请完善表单信息"
      render :new
    end
  end

  def edit
  end

  def update
    if @point.update(strategy_params)
      redirect_to admin_strategies_path, notice: '策略更新成功'
    else
      flash[:warn] = "请完善表单信息"
      render :edit
    end
  end

  def destroy
    @point.destroy
    flash[:notice] = "策略删除成功"
    redirect_to :back
  end

  def change_fettle
    if @point.fettle
      @point.fettle = false
      @point.save
    else
      @point.fettle = true
      @point.save
    end
    render json:{code:200}
  end

  private
    def set_strategy
      @point = Strategy.find(params[:id])
    end

    def strategy_params
      params.require(:strategy).permit(:chain_id, :total, :bulk, :procure, :in_price, :out_price, :fettle)
    end
end

app/views/admin/strategies/_form.html.erb
<%= form_for(['admin',@point]) do |f| %>
<div class="box-body">
  <div class="col-md-5">
    <div class="form-group has-error">
      <label>交易状态</label>
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-money"></i>
        </div>
        <%= f.select(:fettle, [['开启',true],['关闭',false]], {prompt:'请选择货币'},{:class => 'form-control'}) %>
      </div>
      <%= model_errors(@point,'fettle') %>
    </div>
    <div class="form-group has-error">
      <label>区块链</label>
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-btc"></i>
        </div>
        <%= f.select(:chain_id, Chain.all.map{|x| [x.market_name,x.id]}, {prompt:'请选择区块'},{:class => 'form-control'}) %>
      </div>
    </div>
    <div class="form-group has-error">
      <label> 总价值</label>
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-cc"></i>
        </div>
        <%= f.text_field :total, class:'form-control', placeholder:'（必填* 持有区块实际总价值）' %>
      </div>
    </div>
    <div class="form-group has-error">
      <label>次价值</label>
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-cc-jcb"></i>
        </div>
        <%= f.text_field :procure, class:'form-control', placeholder:'（必填* 单次购买的区块数量等价值）' %>
      </div>
    </div>
    <div class="form-group has-error">
      <label>成本价</label>
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-cube"></i>
        </div>
        <%= f.text_field :bulk, class:'form-control', placeholder:'（必填* 实际成本价）' %>
      </div>
    </div>
    <div class="form-group has-error">
      <label>买入价</label>
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-circle"></i>
        </div>
        <%= f.text_field :in_price, class:'form-control', placeholder:'（必填* 买入的最高价）' %>
      </div>
    </div>
    <div class="form-group has-error">
      <label>卖出价</label>
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-circle-o"></i>
        </div>
        <%= f.text_field :out_price, class:'form-control', placeholder:'（必填* 卖出的最低价）' %>
      </div>
    </div>
  </div>
  <div class="col-md-12">
    <hr>
    <div>
      <button type="submit" class="btn bg-maroon btn-flat" style="width: 120px">提交</button>
      <a href="<%= request.referrer %>" class="btn bg-navy btn-flat" style="width: 120px">取消</a>
    </div>
  </div>
</div>
<% end %>

app/views/admin/strategies/edit.html.erb
<%= content_for(:title,  '更新收益策略| BLOCK') %>
<section class="content-header">
  <h1>
    更新收益策略
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> 收益策略</a></li>
    <li><i class="glyphicon glyphicon-edit"></i> 编辑</li>
  </ol>
</section>
<section class="content">
  <div style="padding-top: 10px">
    <div class="box box-warning">
      <div class="box-header">
      </div>
      <%= render 'form' %>
    </div>
  </div>
</section>

app/views/admin/strategies/index.html.erb
<%= content_for(:title,  '收益策略 | BLOCK') %>
<section class="content-header">
  <h1>
    收益策略
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-btc"></i> Dashboard</a></li>
    <li class="active"><i class="fa fa-bandcamp"></i> 收益策略</li>
  </ol>
</section>
<section class="content">
  <div class="box box-primary">
    <div class="box-header">
      <a href="<%= new_admin_strategy_path %>" class="btn bg-primary btn-flat"><i class="ion-plus"></i> 添加策略</a>
    </div>
    <div class="box-body">
      <div class="row">
        <div class="col-sm-12">
          <table id="example1" class="table table-bordered table-striped dataTable" role="grid" aria-describedby="example1_info">
            <thead>
            <tr>
              <th tabindex="0" aria-controls="example1" style="text-align: center">区块链</th>
              <th tabindex="0" aria-controls="example1" style="text-align: center">单价值</th>
              <th tabindex="0" aria-controls="example1" style="text-align: center">成本价</th>
              <th tabindex="0" aria-controls="example1" style="text-align: center">买入价</th>
              <th tabindex="0" aria-controls="example1" style="text-align: center">卖出价</th>
              <th tabindex="0" aria-controls="example1" style="text-align: center">状态</th>
              <th tabindex="0" aria-controls="example1" style="text-align: center;">操作</th>
            </tr>
            </thead>
            <tbody>
            <% @points.each do |item| %>
              <tr style="text-align: center">
                <td>
                  <label class="btn bg-black btn-flat" style="font-size: 16px">
                    <i class="fa fa-btc"></i>
                    <%= item.chain.try(:market_name) %>
                  </label>
                </td>
                <td><%= item.procure %></td>
                <td><%= item.bulk %></td>
                <td><%= item.in_price %></td>
                <td><%= item.out_price %></td>
                <td>
                  <input type="checkbox" name="my-state" <%= 'checked' if item.fettle %> onchange='switch_state(<%= item.id %>)'>
                </td>
                <td>
                  <a href="<%= edit_admin_strategy_path(item) %>" class="btn bg-orange btn-flat">
                    <i class="glyphicon glyphicon-edit"></i>
                  </a>
                  <a href="<%= admin_strategy_path(item) %>" class="btn bg-red btn-flat" data-method="delete" data-confirm="确定删除事务焦点吗？">
                    <i class="glyphicon glyphicon-trash"></i>
                  </a>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-5">
          <div class="dataTables_info" id="example1_info" role="status" aria-live="polite"><h5>总计：「<%= @points.count %>」</h5></div>
        </div>
        <div class="col-sm-12">
          <div class="dataTables_paginate paging_simple_numbers">
          <%= will_paginate @points, :class=>'apple_pagination' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<% content_for :script_footer do %>
  <script type="text/javascript">
    function switch_state(item) {
      $.get('/admin/strategies/' + item +'/change_fettle');
    }
    $("[name='my-state']").bootstrapSwitch({onColor:'success',offColor:'danger'});
  </script>
<% end %>

app/views/admin/strategies/new.html.erb
<%= content_for(:title,  '新增收益策略 | BLOCK') %>
<section class="content-header">
  <h1>
    新增收益策略
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> 收益策略</a></li>
    <li class="active"><i class="glyphicon glyphicon-plus"></i> 新增</li>
  </ol>
</section>
<section class="content">
  <div style="padding-top: 10px">
    <div class="box box-success">
      <div class="box-header">
      </div>
      <%= render 'form' %>
    </div>
  </div>
</section>