config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  devise_for :users
  devise_scope :user do
    get 'sign_in', to:'users/sessions#new'
    post 'sign_in', to:'users/sessions#create'
    get 'sign_up', to:'users/registrations#new'
    post 'sign_up', to:'users/registrations#create'
    get 'sign_out',to:'users/sessions#destroy'
    get 'forgot_password',to:'users/passwords#new'
    post 'forgot_password',to:'users/passwords#create'
    get 'reset_password',to:'users/passwords#edit'
    put 'reset_password',to:'users/passwords#update'
  end

  namespace :admin do
    get '/', to:'dashboard#index', as: :stock
    get 'day_bar', to:'dashboard#day_bar'
    resources :chains do
      resources :markets
    end
    resources :strategies do
      member do
        get 'change_fettle'
      end
    end
    resources :bills
    resources :balances
  end

  namespace :api do
    get 'hit_markets', to:'markets#hit_markets'
    get 'hit_day_bar', to:'markets#hit_day_bar'
    get 'hit_balance', to:'markets#hit_balance'
  end

end

app/views/shared/_banners.html.erb
<div class="banner-content" id="content">
  <div class="page-banner">
    <div class="demo-cont">
      <div class="fnc-slider example-slider">
        <div class="fnc-slider__slides">
          <div class="fnc-slide m--blend-green m--active-slide">
            <a href="/" target="_blank">
              <img src="<%= image_path('A.jpg') %>" class="fnc-slide__inner_banner">
            </a>
          </div>
          <div class="fnc-slide m--blend-green">
            <a href="/" target="_blank">
              <img src="<%= image_path('B.jpg') %>" class="fnc-slide__inner_banner">
            </a>
          </div>
        </div>
        <nav class="fnc-nav">

          <div class="fnc-nav__bgs">
            <div class="fnc-nav__bg m--navbg-green m--active-nav-bg"></div>
            <% 1.times do |i| %>
              <div class="fnc-nav__bg m--navbg-dark"></div>
            <% end %>
          </div>

          <div class="fnc-nav__controls">
            <% 2.times do |i| %>
              <div class="fnc-nav__control">
                <span class="fnc-nav__control-progress"></span>
              </div>
            <% end %>
          </div>
        </nav>
        <div class="dot-right dot-commonRight">
          <img src="<%= image_path('dotRight.png') %>">
        </div>
        <div class="dot-left dot-commonLift">
          <img src="<%= image_path('dotLeft.png') %>">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer id="footer">
  <div class="footer-line">
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center">
          Copyright &copy; <a href="https://www.koogle.cc">Koogle.Zhang</a>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<section id="banner" class="banner">
  <div class="bg-color">
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="col-md-12">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"><img src="<%= image_path('favicon.png') %>" class="img-responsive"></a>
          </div>
          <div class="collapse navbar-collapse navbar-right" id="myNavbar">
            <ul class="nav navbar-nav pc_menu">
              <% if current_user %>
                <li class="user_menu">
                  <a class="herd_user_info" style="min-width: 152px">
                    <img src="<%= image_path('favicon.png') %>">
                    <span>Block</span>
                  </a>
                  <div class="menus">
                    <ul>
                      <%= render partial:'shared/user_link' %>
                    </ul>
                  </div>
                </li>
              <% else %>
                <li><a href="<%= sign_up_path%>">注册&nbsp;<i class="fa fa-user-plus"></i></a></li>
                <li><a href="<%= sign_in_path%>">登录&nbsp;<i class="fa fa-sign-in"></i></a></li>
              <% end %>
            </ul>
            <ul class="nav navbar-nav mobile_menu">
              <% if current_user %>
                <%= render partial:'shared/user_link' %>
              <% else %>
                <li><a href="<%= sign_in_path%>"><i class="fa fa-vcard"></i>&nbsp;&nbsp;注册登录</a></li>
              <% end%>
            </ul>
          </div>
        </div>
      </div>
    </nav>
  </div>
</section>

app/views/shared/_meta.html.erb
<% content_for :meta do %>
  <meta property="og:title" content="<%= @video.title %> | Koogle">
  <meta property="og:type" content="video">
  <meta property="og:url" content="<%= Settings.host + "#{show_path(@video.url_code)}" %>">
  <meta property="og:image" content="<%= video_cover @video.cover %>">
  <meta property="og:site_name" content="在沉默中爆发">
  <meta property="og:description" content="<%= @video.summary || @video.title %>">
<% end %>

app/views/shared/_user_link.html.erb
<li><a href="<%= admin_chains_path %>"><i class="fa fa-gear"></i>&nbsp;&nbsp; 链块管理</a></li>
<li><a href="<%= sign_out_path %>"><i class="fa fa-sign-out"></i>&nbsp;&nbsp;安全登出</a></li>