config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  devise_for :users
  devise_scope :user do
    get 'sign_in', to:'users/sessions#new'
    post 'sign_in', to:'users/sessions#create'
    get 'sign_up', to:'users/registrations#new'
    post 'sign_up', to:'users/registrations#create'
    get 'sign_out',to:'users/sessions#destroy'
    get 'forgot_password',to:'users/passwords#new'
    post 'forgot_password',to:'users/passwords#create'
    get 'reset_password',to:'users/passwords#edit'
    put 'reset_password',to:'users/passwords#update'
  end

  namespace :admin do
    get '/', to:'dashboard#index', as: :stock
    get 'day_bar', to:'dashboard#day_bar'
    resources :chains do
      resources :markets
    end
    resources :strategies do
      member do
        get 'change_fettle'
      end
    end
    resources :bills
    resources :balances
  end

  namespace :api do
    get 'hit_markets', to:'markets#hit_markets'
    get 'hit_day_bar', to:'markets#hit_day_bar'
    get 'hit_balance', to:'markets#hit_balance'
  end

end

app/views/layouts/lte/_flash_msg.html.erb
<div class="row">
  <% if flash[:success] %>
    <div class="col-md-12">
      <div class="box box-success box-solid">
        <div class="box-header with-border">
          <h3 class="box-title">成功信息</h3>
          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="box-body">
          <%= flash[:success] %>
        </div>
      </div>
    </div>
  <% end %>
  <% if flash[:notice] %>
    <div class="col-md-12">
      <div class="box box-info box-solid">
        <div class="box-header with-border">
          <h3 class="box-title">提示信息</h3>
          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="box-body">
          <%= flash[:notice] %>
        </div>
      </div>
    </div>
  <% end %>
  <% if flash[:warn] %>
    <div class="col-md-12">
      <div class="box box-warning box-solid">
        <div class="box-header with-border">
          <h3 class="box-title">警告信息</h3>
          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="box-body">
          <%= flash[:warn] %>
        </div>
      </div>
    </div>
  <% end %>
  <% if flash[:error] %>
    <div class="col-md-12">
      <div class="box box-danger box-solid">
        <div class="box-header with-border">
          <h3 class="box-title">错误信息</h3>
          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="box-body">
          <%= flash[:error] %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/lte/_footer.html.erb
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    <b>Version</b> 2.3.7
  </div>
  <strong>Copyright &copy; 2014-2016 <a href="http://almsaeedstudio.com">Almsaeed Studio</a>.</strong> All rights
  reserved.
</footer>

app/views/layouts/lte/_header.html.erb
<a href="/" class="logo">
  <span class="logo-mini"><b style="font-size: 35px"><i class="fa fa-btc"></i></b></span>
  <span class="logo-lg"><b>Binance</b></span>
</a>
<nav class="navbar navbar-static-top">
  <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
    <span class="sr-only">Toggle navigation</span>
  </a>

  <div class="navbar-custom-menu">
    <ul class="nav navbar-nav">
      <li class="dropdown user user-menu">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <img src="<%= image_path('favicon.png')%>" class="user-image" alt="User Image">
          <span class="hidden-xs"><%= current_user.email.split('@')[0] %></span>
        </a>
        <ul class="dropdown-menu">
          <li class="user-header">
            <img src="<%= image_path('favicon.png')%>" class="img-circle" alt="User Image">
            <p>
              <%= current_user.email.split('@')[0] %> - Web Developer
              <small><%= Time.now.strftime('%Y-%m-%d') %></small>
            </p>
          </li>
          <li class="user-body">
            <div class="row">
              <div class="col-xs-4 text-center">
                <a href="#">Followers</a>
              </div>
              <div class="col-xs-4 text-center">
                <a href="#">Sales</a>
              </div>
              <div class="col-xs-4 text-center">
                <a href="#">Friends</a>
              </div>
            </div>
          </li>
          <li class="user-footer">
            <div class="pull-left">
              <a href="#" class="btn btn-default btn-flat">简介</a>
            </div>
            <div class="pull-right">
              <a href="<%= sign_out_path %>" class="btn btn-default btn-flat">登出</a>
            </div>
          </li>
        </ul>
      </li>
      <li>
        <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/lte/_left_menu.html.erb
<section class="sidebar">
  <div class="user-panel">
    <div class="pull-left image">
      <img src="<%= image_path('favicon.png')%>" class="img-circle" alt="User Image">
    </div>
    <div class="pull-left info">
      <p><%= current_user.email.split('@')[0] %></p>
      <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
    </div>
  </div>
  <form action="#" method="get" class="sidebar-form">
    <div class="input-group">
      <input type="text" name="q" class="form-control" placeholder="Search...">
      <span class="input-group-btn">
        <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
        </button>
      </span>
    </div>
  </form>
  <ul class="sidebar-menu">
    <li class="header">交易中心</li>
    <li class="treeview <%= 'active' if controller_name == 'dashboard' && action_name == 'index'%>">
      <a href="<%= admin_stock_path %>" target="_self">
        <i class="fa fa-dashboard"></i> <span> 五分行情</span>
      </a>
    </li>
    <li class="treeview <%= 'active' if controller_name == 'dashboard' && action_name == 'day_bar'%>">
      <a href="<%= admin_day_bar_path %>" target="_self">
        <i class="fa fa-asterisk"></i> <span> 日线行情</span>
      </a>
    </li>
    <li class="treeview <%= 'active' if controller_name == 'chains' %>">
      <a href="<%= admin_chains_path %>" target="_self">
        <i class="fa fa-btc"></i> <span> 区块货币</span>
      </a>
    </li>
    <% if controller_name == 'markets' %>
      <li class="treeview <%= 'active' if controller_name =='markets' %>">
        <a href="<%= admin_chain_markets_path(params[:chain_id]) %>" target="_self">
          <i class="fa fa-line-chart"></i> <span> 历史行情</span>
        </a>
      </li>
    <% end %>
    <li class="treeview <%= 'active' if controller_name == 'strategies' %>">
      <a href="<%= admin_strategies_path %>" target="_self">
        <i class="fa fa-bandcamp"></i> <span> 收益策略</span>
      </a>
    </li>
    <li class="treeview <%= 'active' if controller_name == 'bills' %>">
      <a href="<%= admin_bills_path %>" target="_self">
        <i class="fa fa-sheqel"></i> <span> 买卖定单</span>
      </a>
    </li>
    <li class="treeview <%= 'active' if controller_name == 'balances' %>">
      <a href="<%= admin_balances_path %>" target="_self">
        <i class="fa fa-gg-circle"></i> <span> 持有余额</span>
      </a>
    </li>
  </ul>
</section>

app/views/layouts/lte/_right_menu.html.erb
<div class="tab-content">
  <div id="control-sidebar-theme-demo-options-tab" class="tab-pane active">
    <%= render :partial => 'layouts/lte/select_skin' %>
    <h4 class="control-sidebar-heading">布局选项</h4>
    <div class="form-group">
      <label class="control-sidebar-subheading"><input type="checkbox" data-layout="fixed" class="pull-right">内容布局</label>
    </div>
    <div class="form-group">
      <label class="control-sidebar-subheading"><input type="checkbox" data-layout="layout-boxed" class="pull-right">盒子布局</label>
    </div>
    <div class="form-group">
      <label class="control-sidebar-subheading"><input type="checkbox" data-layout="sidebar-collapse" class="pull-right">切换侧栏</label>
    </div>
    <div class="form-group">
      <label class="control-sidebar-subheading"><input type="checkbox" data-enable="expandOnHover" class="pull-right">侧栏在悬停时展开</label>
    </div>
    <div class="form-group">
      <label class="control-sidebar-subheading"><input type="checkbox" data-controlsidebar="control-sidebar-open" class="pull-right">切换右侧边栏</label>
    </div>
    <div class="form-group">
      <label class="control-sidebar-subheading"><input type="checkbox" data-sidebarskin="toggle" class="pull-right">切换右侧背景</label>
    </div>
  </div>
</div>

app/views/layouts/lte/_select_skin.html.erb
<h4 class="control-sidebar-heading">个性皮肤</h4>
<ul class="list-unstyled clearfix">
  <li style="float:left; width: 49%; padding: 5px;">
    <a href="javascript:void(0);" data-skin="skin-blue" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
      <div>
        <span style="display:block; width: 20%; float: left; height: 7px; background: #367fa9;"></span>
        <span class="bg-light-blue" style="display:block; width: 80%; float: left; height: 7px;"></span>
      </div>
      <div>
        <span style="display:block; width: 20%; float: left; height: 20px; background: #222d32;"></span>
        <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
      </div>
    </a>
    <p class="text-center no-margin">蓝黑</p>
  </li>
  <li style="float:left; width: 49%; padding: 5px;">
    <a href="javascript:void(0);" data-skin="skin-black" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
      <div style="box-shadow: 0 0 2px rgba(0,0,0,0.1)" class="clearfix">
        <span style="display:block; width: 20%; float: left; height: 7px; background: #fefefe;"></span>
        <span style="display:block; width: 80%; float: left; height: 7px; background: #fefefe;"></span>
      </div>
      <div>
        <span style="display:block; width: 20%; float: left; height: 20px; background: #222;"></span>
        <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
      </div>
    </a>
    <p class="text-center no-margin">白黑</p>
  </li>
  <li style="float:left; width: 49%; padding: 5px;">
    <a href="javascript:void(0);" data-skin="skin-purple" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
      <div>
        <span style="display:block; width: 20%; float: left; height: 7px;" class="bg-purple-active"></span>
        <span class="bg-purple" style="display:block; width: 80%; float: left; height: 7px;"></span>
      </div>
      <div>
        <span style="display:block; width: 20%; float: left; height: 20px; background: #222d32;"></span>
        <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
      </div>
    </a>
    <p class="text-center no-margin">紫黑</p>
  </li>
  <li style="float:left; width: 49%; padding: 5px;">
    <a href="javascript:void(0);" data-skin="skin-green" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
      <div>
        <span style="display:block; width: 20%; float: left; height: 7px;" class="bg-green-active"></span>
        <span class="bg-green" style="display:block; width: 80%; float: left; height: 7px;"></span>
      </div>
      <div>
        <span style="display:block; width: 20%; float: left; height: 20px; background: #222d32;"></span>
        <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
      </div>
    </a>
    <p class="text-center no-margin">绿黑</p>
  </li>
  <li style="float:left; width: 49%; padding: 5px;">
    <a href="javascript:void(0);" data-skin="skin-red" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
      <div>
        <span style="display:block; width: 20%; float: left; height: 7px;" class="bg-red-active"></span>
        <span class="bg-red" style="display:block; width: 80%; float: left; height: 7px;"></span>
      </div>
      <div>
        <span style="display:block; width: 20%; float: left; height: 20px; background: #222d32;"></span>
        <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
      </div>
    </a>
    <p class="text-center no-margin">红黑</p>
  </li>
  <li style="float:left; width: 49%; padding: 5px;">
    <a href="javascript:void(0);" data-skin="skin-yellow" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
      <div>
        <span style="display:block; width: 20%; float: left; height: 7px;" class="bg-yellow-active"></span>
        <span class="bg-yellow" style="display:block; width: 80%; float: left; height: 7px;"></span>
      </div>
      <div>
        <span style="display:block; width: 20%; float: left; height: 20px; background: #222d32;"></span>
        <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
      </div>
    </a>
    <p class="text-center no-margin">黄黑</p>
  </li>
  <li style="float:left; width: 49%; padding: 5px;">
    <a href="javascript:void(0);" data-skin="skin-blue-light" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
      <div>
        <span style="display:block; width: 20%; float: left; height: 7px; background: #367fa9;"></span>
        <span class="bg-light-blue" style="display:block; width: 80%; float: left; height: 7px;"></span>
      </div>
      <div>
        <span style="display:block; width: 20%; float: left; height: 20px; background: #f9fafc;"></span>
        <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
      </div>
    </a>
    <p class="text-center no-margin" style="font-size: 12px">亮蓝</p>
  </li>
  <li style="float:left; width: 49%; padding: 5px;">
    <a href="javascript:void(0);" data-skin="skin-black-light" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
      <div style="box-shadow: 0 0 2px rgba(0,0,0,0.1)" class="clearfix">
        <span style="display:block; width: 20%; float: left; height: 7px; background: #fefefe;"></span>
        <span style="display:block; width: 80%; float: left; height: 7px; background: #fefefe;"></span>
      </div>
      <div>
        <span style="display:block; width: 20%; float: left; height: 20px; background: #f9fafc;"></span>
        <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
      </div>
    </a>
    <p class="text-center no-margin" style="font-size: 12px">亮白</p>
  </li>
  <li style="float:left; width: 49%; padding: 5px;">
    <a href="javascript:void(0);" data-skin="skin-purple-light" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
      <div>
        <span style="display:block; width: 20%; float: left; height: 7px;" class="bg-purple-active"></span>
        <span class="bg-purple" style="display:block; width: 80%; float: left; height: 7px;"></span>
      </div>
      <div>
        <span style="display:block; width: 20%; float: left; height: 20px; background: #f9fafc;"></span>
        <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
      </div>
    </a>
    <p class="text-center no-margin" style="font-size: 12px">亮紫</p>
  </li>
  <li style="float:left; width: 49%; padding: 5px;">
    <a href="javascript:void(0);" data-skin="skin-green-light" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
      <div>
        <span style="display:block; width: 20%; float: left; height: 7px;" class="bg-green-active"></span>
        <span class="bg-green" style="display:block; width: 80%; float: left; height: 7px;"></span>
      </div>
      <div>
        <span style="display:block; width: 20%; float: left; height: 20px; background: #f9fafc;"></span>
        <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
      </div>
    </a>
    <p class="text-center no-margin" style="font-size: 12px">亮绿</p>
  </li>
  <li style="float:left; width: 49%; padding: 5px;">
    <a href="javascript:void(0);" data-skin="skin-red-light" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
      <div>
        <span style="display:block; width: 20%; float: left; height: 7px;" class="bg-red-active"></span>
        <span class="bg-red" style="display:block; width: 80%; float: left; height: 7px;"></span>
      </div>
      <div>
        <span style="display:block; width: 20%; float: left; height: 20px; background: #f9fafc;"></span>
        <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
      </div>
    </a>
    <p class="text-center no-margin" style="font-size: 12px">亮红</p>
  </li>
  <li style="float:left; width: 49%; padding: 5px;">
    <a href="javascript:void(0);" data-skin="skin-yellow-light" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
      <div>
        <span style="display:block; width: 20%; float: left; height: 7px;" class="bg-yellow-active"></span>
        <span class="bg-yellow" style="display:block; width: 80%; float: left; height: 7px;"></span>
      </div>
      <div>
        <span style="display:block; width: 20%; float: left; height: 20px; background: #f9fafc;"></span>
        <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
      </div>
    </a>
    <p class="text-center no-margin" style="font-size: 12px;">亮黄</p>
  </li>
</ul>