config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  devise_for :users
  devise_scope :user do
    get 'sign_in', to:'users/sessions#new'
    post 'sign_in', to:'users/sessions#create'
    get 'sign_up', to:'users/registrations#new'
    post 'sign_up', to:'users/registrations#create'
    get 'sign_out',to:'users/sessions#destroy'
    get 'forgot_password',to:'users/passwords#new'
    post 'forgot_password',to:'users/passwords#create'
    get 'reset_password',to:'users/passwords#edit'
    put 'reset_password',to:'users/passwords#update'
  end

  namespace :admin do
    get '/', to:'dashboard#index', as: :stock
    get 'day_bar', to:'dashboard#day_bar'
    resources :chains do
      resources :markets
    end
    resources :strategies do
      member do
        get 'change_fettle'
      end
    end
    resources :bills
    resources :balances
  end

  namespace :api do
    get 'hit_markets', to:'markets#hit_markets'
    get 'hit_day_bar', to:'markets#hit_day_bar'
    get 'hit_balance', to:'markets#hit_balance'
  end

end

app/models/chain.rb
# t.string   "block",      limit: 255
# t.string   "currency",   limit: 255
# t.string   "title",      limit: 255
# t.datetime "created_at",             null: false
# t.datetime "updated_at",             null: false
require 'openssl'
OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE
class Chain < ActiveRecord::Base
  self.per_page = 10
  validates_presence_of :block, :currency, :title
  validates_uniqueness_of :block, scope: :currency
  has_many :markets, class_name:'Market'
  has_many :bills, class_name:'Bill'
  has_many :day_bars, class_name:'DayBar'
  has_one  :usdt, class_name:'Chain', foreign_key:'block', primary_key: 'currency'
  has_one  :strategy
  has_one  :balance, class_name:'Balance', primary_key: 'block', foreign_key:'block'
  has_one  :wallet, class_name:'Balance', primary_key: 'currency', foreign_key:'block'

  def market_name
    "#{self.block}-#{self.currency}"
  end

  def symbol
    "#{self.block}#{self.currency}"
  end

  def get_market(interval,amount)
    market_url = 'https://api.binance.com/api/v1/klines'
    res = Faraday.get do |req|
      req.url market_url
      req.params['symbol'] = self.symbol
      req.params['interval'] = interval
      req.params['limit'] = amount
    end
    current = JSON.parse(res.body)
  end

  def high
    self.markets.timing.last(96).map {|x| x.c_price }.max
  end

  def low
    self.markets.timing.last(96).map {|x| x.c_price }.min
  end

  def last
    self.markets.timing.last.c_price
  end

  def retain_balance
    self.balance.try(:balance) || 0
  end

  def retain_money
    self.wallet.try(:balance) || 0
  end

  def total_bulk
    self.strategy.try(:bulk) || 0
  end

  def total_money
    self.strategy.try(:total) || 0
  end

  def in_price
    self.strategy.try(:in_price) || 0
  end

  def out_price
    self.strategy.try(:out_price) || 0
  end

  def procure
    self.strategy.try(:procure) || 0
  end

  def usdt_price
    if self.currency != 'USDT'
      usdt = self.usdt.last
      return (usdt * self.last).round(2)
    else
      return self.last.round(2)
    end
  end

  def self.wechat_notice(title,content)
    push_url = 'https://sc.ftqq.com/SCU16737Tfd4e2c97f2d967e26cd629f1f87ca4345a1bc153e6755.send'
    res = Faraday.get do |req|
      req.url push_url
      req.params['text'] = title
      req.params['desp'] = content
    end
  end

  def self.sms_yunpian(mobile,content)
    yunpian = 'https://sms.yunpian.com/v2/sms/tpl_single_send.json'
    params = {}
    params[:apikey] = Settings.yunpian_key
    params[:tpl_id] = '1950240'
    params[:mobile] = mobile
    params[:tpl_value] = URI::escape('#report#') + '='+ URI::escape(content)
    Faraday.send(:post,yunpian, params)
  end

end

app/controllers/admin/chains_controller.rb
class Admin::ChainsController < Admin::BaseController
  before_action :set_chain, only: [:show, :edit, :update, :destroy]

  def index
    @chains = Chain.paginate(page:params[:page])
  end

  def show
  end

  def new
    @chain = Chain.new
  end

  def edit
  end

  def create
    @chain = Chain.new(chain_params)
    if @chain.save
      redirect_to admin_chains_path, notice: '块链添加成功'
    else
      render :new
    end
  end

  def update
    if @chain.update(chain_params)
      redirect_to admin_chains_path, notice: '块链更新成功'
    else
      render :edit
    end
  end

  def destroy
    @chain.destroy
    redirect_to :back, notice: '块链删除成功'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chain
      @chain = Chain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chain_params
      params.require(:chain).permit(:block, :currency, :title)
    end

end

app/views/admin/chains/_form.html.erb
<%= form_for(['admin',@chain]) do |f| %>
<div class="box-body">
  <div class="col-md-5">
    <div class="form-group has-error">
      <label>区块</label>
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-btc"></i>
        </div>
        <%= f.text_field :block, class:'form-control', placeholder:'（必填* 区块链）' %>
      </div>
      <%= model_errors(@chain,'block') %>
    </div>
    <div class="form-group has-error">
      <label>货币</label>
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-money"></i>
        </div>
        <%= f.select(:currency, [['美元','USDT'],['比特币','BTC'],['以太币','ETH']], {prompt:'请选择货币'},{:class => 'form-control'}) %>
      </div>
      <%= model_errors(@chain,'currency') %>
    </div>
    <div class="form-group has-error">
      <label>标签</label>
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-cc-mastercard"></i>
        </div>
        <%= f.text_field :title, class:'form-control', placeholder:'（必填* 区块链名称）' %>
      </div>
      <%= model_errors(@chain,'title') %>
    </div>
  </div>
  <div class="col-md-12">
    <hr>
    <div>
      <button type="submit" class="btn bg-maroon btn-flat" style="width: 120px">提交</button>
      <a href="<%= request.referrer %>" class="btn bg-navy btn-flat" style="width: 120px">取消</a>
    </div>
  </div>
</div>
<% end %>

app/views/admin/chains/edit.html.erb
<%= content_for(:title,  '编辑区块链| BLOCK') %>
<section class="content-header">
  <h1>
    区块链
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> 区块链管理</a></li>
    <li><i class="glyphicon glyphicon-edit"></i> 编辑区块</li>
  </ol>
</section>
<section class="content">
  <div style="padding-top: 10px">
    <div class="box box-warning">
      <div class="box-header">
        <h3 class="box-title">编辑表单</h3>
      </div>
      <%= render 'form' %>
    </div>
  </div>
</section>

app/views/admin/chains/index.html.erb
<%= content_for(:title,  '区块链列表 | BLOCK') %>
<section class="content-header">
  <h1>
    区块链 <small>信息预览</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-btc"></i> Dashboard</a></li>
    <li class="active"><i class="fa fa-btc"></i> 区块链</li>
  </ol>
</section>
<section class="content">
  <div class="box box-primary">
    <div class="box-header">
      <a href="<%= new_admin_chain_path %>" class="btn bg-primary btn-flat"><i class="ion-plus"></i> 添加区块</a>
    </div>
    <div class="box-body">
      <div class="row">
        <div class="col-sm-12">
          <table id="example1" class="table table-bordered table-striped dataTable" role="grid" aria-describedby="example1_info">
            <thead>
            <tr>
              <th tabindex="0" aria-controls="example1" style="text-align: center">区块</th>
              <th tabindex="0" aria-controls="example1" style="text-align: center">货币</th>
              <th tabindex="0" aria-controls="example1" style="text-align: center">名称</th>
              <th tabindex="0" aria-controls="example1" style="text-align: center;width: 240px">操作</th>
            </tr>
            </thead>
            <tbody>
            <% @chains.each do |item| %>
              <tr style="text-align: center">
                <td>
                  <label class="btn bg-black btn-flat" style="font-size: 16px">
                    <i class="fa fa-btc"></i>
                    <%= item.block %>
                  </label>
                </td>
                <td>
                  <label class="btn bg-black btn-flat" style="font-size: 16px">
                    <i class="fa fa-money"></i>
                    <%= item.currency %>
                  </label>
                </td>
                <td>
                  <label class="btn bg-black btn-flat" style="font-size: 16px">
                    <i class="fa fa-cc-mastercard"></i>
                    <%= item.title %>
                  </label>
                </td>
                <td>
                  <a href="<%= admin_chain_markets_path(item) %>" class="btn bg-green btn-flat">
                    <i class="fa fa-area-chart"></i>
                  </a>
                  <a href="<%= edit_admin_chain_path(item) %>" class="btn bg-orange btn-flat">
                    <i class="glyphicon glyphicon-edit"></i>
                  </a>
                  <a href="<%= admin_chain_path(item) %>" class="btn bg-red btn-flat" data-method="delete" data-confirm="确定删除该块链吗？">
                    <i class="glyphicon glyphicon-trash"></i>
                  </a>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-5">
          <div class="dataTables_info" id="example1_info" role="status" aria-live="polite"><h5>总计：「<%= @chains.count %>」种类</h5></div>
        </div>
        <div class="col-sm-12">
          <div class="dataTables_paginate paging_simple_numbers">
          <%= will_paginate @chains, :class=>'apple_pagination' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/chains/new.html.erb
<%= content_for(:title,  '添加新区块链 | BLOCK') %>
<section class="content-header">
  <h1>
    添加区块链
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> 区块管理</a></li>
    <li class="active"><i class="glyphicon glyphicon-plus"></i> 新增区块</li>
  </ol>
</section>
<section class="content">
  <div style="padding-top: 10px">
    <div class="box box-success">
      <div class="box-header">
        <h3 class="box-title">新增表单</h3>
      </div>
      <%= render 'form' %>
    </div>
  </div>
</section>